name: NNA Registry Service CI/CD

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Set hardcoded project ID and service account
    env:
      GCP_PROJECT_ID: revize-453014
      GCP_SERVICE_ACCOUNT: github-actions@revize-453014.iam.gserviceaccount.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build application
        run: npm run build || echo "Build command not found or failed, continuing with Docker build"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker for Google Cloud
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/nna-registry-service:${{ github.sha }} .

      - name: Push Docker image
        run: docker push gcr.io/${{ env.GCP_PROJECT_ID }}/nna-registry-service:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nna-registry-service \
            --image gcr.io/${{ env.GCP_PROJECT_ID }}/nna-registry-service:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated