name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          echo "REACT_APP_API_URL=/api" > .env.production
          echo "REACT_APP_USE_MOCK_API=false" >> .env.production
        
      - name: Build project
        run: CI=false npm run build
        
      - name: Log build success
        run: |
          echo "✅ Build completed successfully"
          echo "To deploy, use the Vercel CLI: vercel --prod"