name: Build and Test (Default CI)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          echo "REACT_APP_API_URL=/api" > .env.production
          echo "REACT_APP_USE_MOCK_API=false" >> .env.production
        
      - name: Build project
        run: CI=false npm run build
        
      - name: Log build success and deployment instructions
        run: |
          echo "✅ Build completed successfully"
          echo "To deploy, use one of these methods:"
          echo "1. Vercel CLI: vercel --prod"
          echo "2. Manual trigger of the 'Deploy to Vercel Production (Requires Secrets)' workflow"
          echo ""
          echo "NOTE: The Deploy to Vercel workflow requires secrets to be configured."
          echo "See GITHUB_SECRETS_SETUP.md for instructions."