name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - feature/dashboard-and-integration
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Check for build errors
        run: |
          echo "Running build check..."
          if ! npm run build; then
            echo "::error::Build failed! Please check your code for errors."
            exit 1
          fi
      
      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod'
      
      - name: Verify deployment
        run: |
          if [ -z "${{ steps.deploy.outputs.preview-url }}" ]; then
            echo "::warning::No preview URL was returned by Vercel, deployment may have failed."
          else
            echo "::notice::Deployment successful! Site is live at ${{ steps.deploy.outputs.preview-url }}"
            echo "Running basic health check..."
            
            # Wait a bit for the deployment to stabilize
            sleep 10
            
            # Basic health check
            if curl -s -o /dev/null -w "%{http_code}" "${{ steps.deploy.outputs.preview-url }}" | grep -q "200\|301\|302"; then
              echo "::notice::Health check passed! Site is responding with expected status code."
            else
              echo "::warning::Health check failed! Site is not responding with expected status code."
            fi
          fi