name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - feature/dashboard-and-integration
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Check for build errors
        run: |
          echo "Running build check..."
          # Set CI=false to prevent treating warnings as errors
          CI=false npm run build || {
            echo "::error::Build failed! Please check your code for errors."
            exit 1
          }
      
      - name: Create build artifact for manual deployment
        run: |
          echo "::notice::Creating build artifact for manual deployment..."
          # Compress the build directory
          tar -czf build.tar.gz build/
          
          # Save the artifact
          echo "::notice::Build artifact created. You can now download the build.tar.gz file and deploy manually to Vercel."
          echo "::notice::Alternatively, setup Vercel project secrets in GitHub repository settings:"
          echo "::notice::1. VERCEL_TOKEN: Your Vercel API token"
          echo "::notice::2. VERCEL_ORG_ID: Your Vercel organization ID"
          echo "::notice::3. VERCEL_PROJECT_ID: Your Vercel project ID"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build.tar.gz
          retention-days: 7