name: Development Auto-Deploy

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}

jobs:
  test-and-deploy:
    name: Test & Deploy to Development
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Build Test
      run: CI=false npm run build
      
    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}

    - name: Use Development Vercel Configuration
      run: cp vercel.development.json vercel.json

    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Development Environment
      run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  health-check:
    name: Development Health Check
    runs-on: ubuntu-latest
    needs: test-and-deploy
    if: github.ref == 'refs/heads/development'
    
    steps:
    - name: Wait for Deployment
      run: sleep 30

    - name: Test Development Environment
      run: curl -f https://nna-registry-frontend-dev.vercel.app/ || exit 1

    - name: Notify Success
      if: success()
      run: echo "🎉 Development deployment successful and healthy!"

    - name: Notify Failure
      if: failure()
      run: |
        echo "❌ Development deployment failed or unhealthy"
        exit 1